"""
fit_memristor_pso.py
====================
Guided particle-swarm parameter extraction for a bipolar memristive-device
compact model simulated with NGSpice.

The script performs two stages:

1. Coarse fitting on a reduced set of measurement points.
2. Refined fitting on the complete measured I-V trajectory.

The fitted SPICE template and best parameter table are written to
``results/fit/``. The two analysis programs in this repository read those
outputs directly.
"""

from __future__ import annotations

import json
import math
import re
import shutil
import subprocess
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Callable

import numpy as np
import pandas as pd


# =============================================================================
# Paths
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent
PRIVATE_DATA = BASE_DIR / "data" / "DC-IV.csv"
SYNTHETIC_DATA = BASE_DIR / "data" / "example_synthetic.csv"

_ngspice_on_path = shutil.which("ngspice")
NGSPICE = Path(_ngspice_on_path) if _ngspice_on_path else BASE_DIR / "ngspice.exe"

OUT_DIR = BASE_DIR / "results" / "fit"
LOG_DIR = OUT_DIR / "fit_logs"
DECK_DIR = OUT_DIR / "fit_decks"
SIM_DIR = OUT_DIR / "fit_sims"
TEMPLATE_PATH = OUT_DIR / "fitdeck_embedded.cir"


# =============================================================================
# Reproducibility and PSO settings
# =============================================================================

RANDOM_SEED = 7

N_PARTICLES_COARSE = 20
N_ITERATIONS_COARSE = 60
N_PARTICLES_REFINE = 18
N_ITERATIONS_REFINE = 60
COARSE_POINT_TARGET = 220

INERTIA_MAX = 0.85
INERTIA_MIN = 0.40
COGNITIVE_COEFF = 1.5
SOCIAL_COEFF = 1.5

REFINE_LINEAR_JITTER = 0.08
REFINE_LOG_JITTER_DECADES = 0.25

TSTOP = 10.0
DTMAX = 2e-4
PRINT_DIV = 6
PRINT_MIN = 2e-5
PRINT_MAX = 4e-3
NGSPICE_TIMEOUT_S = 180

I_FLOOR = 3e-10
FAIL_COST = 1e9


# =============================================================================
# Fixed model settings
# =============================================================================

FIXED_KNOBS = {
    "KSW": 3.0,
    "RH0": 1e3,
    "RH_MIN": 1.0,
    "RH_MAX": 1e7,
    "VSLOPE": 0.5,
}

COMPLIANCE_SETTINGS = {
    "VCOMP": 0.0,
    "RLO": 1.0,
    "RHI": 2e8,
    "VSLOPE_POS": 0.02,
    "ISLOPE_REL": 0.02,
}

PARAMETERS = [
    "IMAX",
    "IMIN",
    "ALPHA_MAX",
    "ALPHA_MIN",
    "BETAA",
    "VSET",
    "VRES",
    "ETA_SET",
    "ETA_RES",
    "CH0",
    "ISCALE",
    "H0",
    "EI",
    "ROFF",
]

BOUNDS: dict[str, tuple[float, float]] = {
    "IMAX": (1e-7, 2e-1),
    "IMIN": (1e-10, 5e-4),
    "ALPHA_MAX": (0.8, 15.0),
    "ALPHA_MIN": (1e-6, 12.0),
    "BETAA": (0.05, 0.95),
    "VSET": (0.2, 20.0),
    "VRES": (0.2, 20.0),
    "ETA_SET": (0.3, 120.0),
    "ETA_RES": (1e-6, 35.0),
    "CH0": (1e-12, 3e-5),
    "ISCALE": (1e-10, 3e-1),
    "H0": (1e-6, 0.97),
    "EI": (1e-16, 1e-3),
    "ROFF": (1e6, 1e14),
}

LOG_PARAMETERS = {
    "IMAX",
    "IMIN",
    "ETA_SET",
    "ETA_RES",
    "CH0",
    "ISCALE",
    "EI",
    "ROFF",
}


# =============================================================================
# Embedded NGSpice template
# =============================================================================

FITDECK_TEMPLATE = r"""* ============================================================
* Fitted bipolar memristive-device model
* Generated by fit_memristor_pso.py
* ============================================================

Vcmd vc 0 PWL(
@PWL_INLINE@
+ )

Vsen vc p0 0

.param ICOMP = @ICOMP_POS@
.param VCOMP = @VCOMP@
.param RLO = @RLO@
.param RHI = @RHI@
.param ISLOPE = @ISLOPE@
.param VSLOPE_POS = @VSLOPE_POS@

.func smooth_step(u) { 0.5*(1+tanh(u)) }
.func positive_gate(v) { smooth_step((v-VCOMP)/VSLOPE_POS) }
.func current_gate(i) { smooth_step((abs(i)-ICOMP)/ISLOPE) }

Rlim p0 p r={RLO+(RHI-RLO)*positive_gate(V(vc))*current_gate(i(Vsen))}
X1 p 0 x xh memdiode_bipolar CH0=@CH0@ H0=@H0@

.options method=gear reltol=4e-3 abstol=2e-15 vntol=2e-9
+ chgtol=2e-16 gmin=1e-12 itl1=900 itl4=350

.control
  set noaskquit
  set filetype=ascii
  set wr_singlescale
  tran @TSTEP@ @TSTOP@ 0 @DTMAX@ uic
  wrdata @SIMOUT@ v(vc) v(p) i(Vcmd) v(x) v(xh)
  quit
.endc

.subckt memdiode_bipolar p n x xh CH0=@CH0@ H0=@H0@

.param RH0=@RH0@
.param RH_MIN=@RH_MIN@
.param RH_MAX=@RH_MAX@
.param VSLOPE=@VSLOPE@

.param IMAX=@IMAX@
.param IMIN=@IMIN@
.param ALPHAMX=@ALPHA_MAX@
.param ALPHAMN=@ALPHA_MIN@
.param BETA=@BETAA@
.param VSET=@VSET@
.param VRES=@VRES@
.param ETA_SET=@ETA_SET@
.param ETA_RES=@ETA_RES@
.param ISCALE=@ISCALE@
.param EI=@EI@
.param ROFF=@ROFF@
.param CPAR=1p

.func softclip(v) {0.5*(tanh(4*(v-0.5))+1)}
.func blend(w,a,b) {w*a+(1-w)*b}
.func safe_exp(v) {exp(min(max(v,-25),25))}
.func sstep(v) {0.5*(1+tanh(v/VSLOPE))}
.func I0(h) {IMAX*h+IMIN*(1-h)}
.func Acoef(h) {ALPHAMX*h+ALPHAMN*(1-h)}
.func Stau(v) {RH0*safe_exp(-ETA_SET*(v-VSET))}
.func Rtau(v) {RH0*safe_exp(ETA_RES*(v+VRES))}
.func Idiff(v,h) {safe_exp(BETA*Acoef(h)*v)-safe_exp(-(1-BETA)*Acoef(h)*v)}

Bxh xh 0 V={softclip(V(x))}
Rs p d 1
BA A 0 V={sstep(V(d,n))}
Rh x A r={min(RH_MAX,max(RH_MIN,blend(V(A),Stau(V(d,n)),Rtau(V(d,n)))))}
Cx x 0 {CH0} ic={H0}
Rxl x 0 1e12
Bcond d n I={ISCALE*(I0(V(xh))*Idiff(V(d,n),V(xh))+EI*V(d,n))}
Rleak d n {ROFF}
Cpar d 0 {CPAR}

.ends memdiode_bipolar
.end
"""


# =============================================================================
# Data classes
# =============================================================================

@dataclass
class SimulationResult:
    time: np.ndarray
    vcmd: np.ndarray
    vp: np.ndarray
    current: np.ndarray
    x: np.ndarray
    xh: np.ndarray


# =============================================================================
# File and data utilities
# =============================================================================


def ensure_directories() -> None:
    for directory in (OUT_DIR, LOG_DIR, DECK_DIR, SIM_DIR):
        directory.mkdir(parents=True, exist_ok=True)
    TEMPLATE_PATH.write_text(FITDECK_TEMPLATE, encoding="utf-8")


def select_measurement_path() -> Path:
    if PRIVATE_DATA.exists():
        return PRIVATE_DATA
    if SYNTHETIC_DATA.exists():
        print(
            "[WARN] data/DC-IV.csv was not found; using the public synthetic "
            "example instead."
        )
        return SYNTHETIC_DATA
    raise FileNotFoundError(
        "Missing data/DC-IV.csv. A synthetic fallback may be stored as "
        "data/example_synthetic.csv."
    )


def read_measurement(path: Path) -> tuple[np.ndarray, np.ndarray]:
    table = pd.read_csv(path, engine="python")
    if table.shape[1] < 2:
        raise ValueError("The measurement CSV must contain at least two columns.")

    voltage = pd.to_numeric(table.iloc[:, 0], errors="coerce")
    current = pd.to_numeric(table.iloc[:, 1], errors="coerce")
    valid = voltage.notna() & current.notna()

    v = voltage[valid].to_numpy(dtype=float)
    i = current[valid].to_numpy(dtype=float)
    if len(v) < 20:
        raise ValueError("Too few numeric measurement rows remain after cleaning.")
    return v, i


def estimate_positive_compliance(voltage: np.ndarray, current: np.ndarray) -> float:
    mask = voltage > 0.5
    if not np.any(mask):
        return 1e-3
    estimate = float(np.quantile(np.abs(current[mask]), 0.98))
    return float(np.clip(estimate, 1e-6, 5e-2))


def pick_print_step(point_count: int, tstop: float) -> float:
    dt_command = tstop / max(point_count - 1, 1)
    return float(np.clip(dt_command / PRINT_DIV, PRINT_MIN, PRINT_MAX))


def make_pwl(voltage: np.ndarray, tstop: float, pairs_per_line: int = 8) -> str:
    time = np.linspace(0.0, tstop, len(voltage))
    pairs = [f"{t:.12g} {v:.12g}" for t, v in zip(time, voltage)]
    return "\n".join(
        "+ " + " ".join(pairs[start : start + pairs_per_line])
        for start in range(0, len(pairs), pairs_per_line)
    )


def safe_tag(text: str) -> str:
    text = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(text))
    return re.sub(r"_+", "_", text).strip("_")


# =============================================================================
# Parameter encoding
# =============================================================================


def encode_parameters(theta: dict[str, float]) -> np.ndarray:
    encoded = []
    for name in PARAMETERS:
        value = float(theta[name])
        encoded.append(math.log10(value) if name in LOG_PARAMETERS else value)
    return np.asarray(encoded, dtype=float)


def decode_parameters(position: np.ndarray) -> dict[str, float]:
    theta: dict[str, float] = {}
    for index, name in enumerate(PARAMETERS):
        value = float(position[index])
        theta[name] = 10.0**value if name in LOG_PARAMETERS else value
    return clip_theta(theta)


def encoded_bounds() -> tuple[np.ndarray, np.ndarray]:
    lower = []
    upper = []
    for name in PARAMETERS:
        lo, hi = BOUNDS[name]
        if name in LOG_PARAMETERS:
            lower.append(math.log10(lo))
            upper.append(math.log10(hi))
        else:
            lower.append(lo)
            upper.append(hi)
    return np.asarray(lower, dtype=float), np.asarray(upper, dtype=float)


def clip_theta(theta: dict[str, float]) -> dict[str, float]:
    return {
        name: float(np.clip(theta[name], BOUNDS[name][0], BOUNDS[name][1]))
        for name in PARAMETERS
    }


# =============================================================================
# NGSpice simulation
# =============================================================================


def render_deck(
    theta: dict[str, float],
    voltage: np.ndarray,
    sim_path: Path,
    icomp: float,
) -> str:
    tstep = pick_print_step(len(voltage), TSTOP)
    islope = max(1e-12, COMPLIANCE_SETTINGS["ISLOPE_REL"] * icomp)

    replacements: dict[str, str] = {
        "@PWL_INLINE@": make_pwl(voltage, TSTOP),
        "@SIMOUT@": str(sim_path),
        "@TSTEP@": f"{tstep:.12g}",
        "@DTMAX@": f"{DTMAX:.12g}",
        "@TSTOP@": f"{TSTOP:.12g}",
        "@ICOMP_POS@": f"{icomp:.12g}",
        "@VCOMP@": f"{COMPLIANCE_SETTINGS['VCOMP']:.12g}",
        "@RLO@": f"{COMPLIANCE_SETTINGS['RLO']:.12g}",
        "@RHI@": f"{COMPLIANCE_SETTINGS['RHI']:.12g}",
        "@ISLOPE@": f"{islope:.12g}",
        "@VSLOPE_POS@": f"{COMPLIANCE_SETTINGS['VSLOPE_POS']:.12g}",
    }

    for name, value in FIXED_KNOBS.items():
        replacements[f"@{name}@"] = f"{value:.12g}"
    for name, value in theta.items():
        replacements[f"@{name}@"] = f"{value:.12g}"

    text = FITDECK_TEMPLATE
    for token, replacement in replacements.items():
        text = text.replace(token, replacement)

    leftovers = sorted(set(re.findall(r"@[A-Za-z0-9_]+@", text)))
    if leftovers:
        raise RuntimeError(f"Unreplaced SPICE placeholders: {leftovers}")
    return text


def run_simulation(
    theta: dict[str, float],
    voltage: np.ndarray,
    icomp: float,
    tag: str,
) -> SimulationResult | None:
    tag = safe_tag(tag)
    deck_path = DECK_DIR / f"{tag}.cir"
    log_path = LOG_DIR / f"{tag}.log"
    sim_path = SIM_DIR / f"{tag}.dat"

    deck_path.write_text(
        render_deck(theta, voltage, sim_path, icomp),
        encoding="utf-8",
    )

    try:
        completed = subprocess.run(
            [str(NGSPICE), "-b", "-o", str(log_path), str(deck_path)],
            cwd=str(OUT_DIR),
            timeout=NGSPICE_TIMEOUT_S,
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None

    if completed.returncode != 0 or not sim_path.exists():
        return None

    try:
        data = np.loadtxt(sim_path, dtype=float)
    except (OSError, ValueError):
        return None

    if data.ndim == 1:
        data = data.reshape(1, -1)
    if data.shape[1] < 6 or len(data) < 8:
        return None

    return SimulationResult(
        time=data[:, 0],
        vcmd=data[:, 1],
        vp=data[:, 2],
        current=data[:, 3],
        x=data[:, 4],
        xh=data[:, 5],
    )


# =============================================================================
# Objective function
# =============================================================================


def build_region_weights(voltage: np.ndarray, current: np.ndarray) -> np.ndarray:
    abs_v = np.abs(voltage)
    abs_i = np.abs(current)
    weights = np.ones_like(voltage, dtype=float)

    # Near-zero behavior and loop closure.
    weights[abs_v <= 0.25] *= 1.8

    # Positive SET region and positive high-resistance branch.
    weights[(voltage >= 0.5) & (voltage <= 4.0)] *= 1.4
    weights[voltage >= 4.0] *= 1.25

    # Negative RESET branch receives extra emphasis because its current can be
    # much smaller than the positive branch in absolute units.
    weights[voltage < -0.5] *= 1.8
    weights[voltage < -3.0] *= 1.35

    # Emphasize the measured switching knee without letting isolated points
    # dominate the objective.
    if np.any(abs_i > I_FLOOR):
        log_i = np.log10(abs_i + I_FLOOR)
        gradient = np.abs(np.gradient(log_i))
        threshold = np.quantile(gradient, 0.88)
        weights[gradient >= threshold] *= 1.5

    return weights / np.mean(weights)


def aligned_simulation_current(
    result: SimulationResult,
    target_count: int,
) -> np.ndarray:
    phase = result.time / max(float(result.time[-1]), 1e-30)
    target_phase = np.linspace(0.0, 1.0, target_count)
    return np.interp(target_phase, phase, result.current)


def calculate_cost(
    measured_current: np.ndarray,
    simulated_current: np.ndarray,
    weights: np.ndarray,
    xh: np.ndarray,
) -> float:
    measured_log = np.log10(np.abs(measured_current) + I_FLOOR)
    simulated_log = np.log10(np.abs(simulated_current) + I_FLOOR)

    log_error = np.average((simulated_log - measured_log) ** 2, weights=weights)

    measured_scale = np.quantile(np.abs(measured_current), 0.95) + I_FLOOR
    signed_error = np.average(
        ((simulated_current - measured_current) / measured_scale) ** 2,
        weights=weights,
    )

    # Encourage a meaningful internal-state span and bounded effective state.
    xh_span = float(np.max(xh) - np.min(xh))
    state_penalty = max(0.0, 0.12 - xh_span) ** 2 * 20.0
    bound_penalty = float(np.mean(np.maximum(0.0, -xh) ** 2 + np.maximum(0.0, xh - 1.0) ** 2))

    total = float(log_error + 0.15 * signed_error + state_penalty + 10.0 * bound_penalty)
    return total if np.isfinite(total) else FAIL_COST


def make_objective(
    voltage: np.ndarray,
    current: np.ndarray,
    icomp: float,
    stage: str,
) -> Callable[[dict[str, float], int], float]:
    weights = build_region_weights(voltage, current)

    def objective(theta: dict[str, float], evaluation_index: int) -> float:
        result = run_simulation(
            theta,
            voltage,
            icomp,
            tag=f"{stage}_{evaluation_index:07d}",
        )
        if result is None:
            return FAIL_COST

        simulated = aligned_simulation_current(result, len(current))
        return calculate_cost(current, simulated, weights, result.xh)

    return objective


# =============================================================================
# Particle swarm optimization
# =============================================================================


def latin_hypercube_positions(
    rng: np.random.Generator,
    count: int,
    lower: np.ndarray,
    upper: np.ndarray,
) -> np.ndarray:
    dimensions = len(lower)
    positions = np.empty((count, dimensions), dtype=float)
    for dimension in range(dimensions):
        points = (np.arange(count) + rng.random(count)) / count
        rng.shuffle(points)
        positions[:, dimension] = lower[dimension] + points * (
            upper[dimension] - lower[dimension]
        )
    return positions


def run_pso(
    *,
    objective: Callable[[dict[str, float], int], float],
    particle_count: int,
    iteration_count: int,
    rng: np.random.Generator,
    initial_center: dict[str, float] | None = None,
) -> tuple[dict[str, float], float, list[dict[str, float]]]:
    lower, upper = encoded_bounds()
    dimensions = len(lower)

    if initial_center is None:
        positions = latin_hypercube_positions(rng, particle_count, lower, upper)
    else:
        center = encode_parameters(initial_center)
        positions = np.tile(center, (particle_count, 1))
        for index, name in enumerate(PARAMETERS):
            if name in LOG_PARAMETERS:
                positions[:, index] += rng.normal(
                    0.0, REFINE_LOG_JITTER_DECADES, particle_count
                )
            else:
                width = upper[index] - lower[index]
                positions[:, index] += rng.normal(
                    0.0, REFINE_LINEAR_JITTER * width, particle_count
                )
        positions[0] = center
        positions = np.clip(positions, lower, upper)

    velocity_scale = 0.08 * (upper - lower)
    velocities = rng.normal(0.0, velocity_scale, size=(particle_count, dimensions))

    personal_positions = positions.copy()
    personal_costs = np.full(particle_count, np.inf)
    global_position = positions[0].copy()
    global_cost = np.inf
    history: list[dict[str, float]] = []
    evaluation_index = 0

    for iteration in range(iteration_count):
        for particle in range(particle_count):
            evaluation_index += 1
            theta = decode_parameters(positions[particle])
            cost = objective(theta, evaluation_index)

            if cost < personal_costs[particle]:
                personal_costs[particle] = cost
                personal_positions[particle] = positions[particle].copy()
            if cost < global_cost:
                global_cost = cost
                global_position = positions[particle].copy()

        progress = iteration / max(iteration_count - 1, 1)
        inertia = INERTIA_MAX + progress * (INERTIA_MIN - INERTIA_MAX)

        r1 = rng.random((particle_count, dimensions))
        r2 = rng.random((particle_count, dimensions))
        velocities = (
            inertia * velocities
            + COGNITIVE_COEFF * r1 * (personal_positions - positions)
            + SOCIAL_COEFF * r2 * (global_position - positions)
        )
        positions = np.clip(positions + velocities, lower, upper)

        history.append(
            {
                "iteration": float(iteration + 1),
                "best_cost": float(global_cost),
            }
        )
        print(
            f"[PSO] iteration {iteration + 1:03d}/{iteration_count:03d} "
            f"best_cost={global_cost:.6g}"
        )

    return decode_parameters(global_position), float(global_cost), history


# =============================================================================
# Reporting
# =============================================================================


def export_theta(theta: dict[str, float]) -> None:
    table = pd.DataFrame(
        {"param": PARAMETERS, "value": [theta[name] for name in PARAMETERS]}
    )
    table.to_csv(OUT_DIR / "theta_best.csv", index=False)


def export_run_configuration(data_path: Path, icomp: float) -> None:
    configuration = {
        "saved_at": datetime.now().isoformat(timespec="seconds"),
        "data_path": str(data_path),
        "ngspice": str(NGSPICE),
        "random_seed": RANDOM_SEED,
        "coarse_particles": N_PARTICLES_COARSE,
        "coarse_iterations": N_ITERATIONS_COARSE,
        "refine_particles": N_PARTICLES_REFINE,
        "refine_iterations": N_ITERATIONS_REFINE,
        "estimated_positive_compliance_A": icomp,
        "fixed_knobs": FIXED_KNOBS,
        "bounds": {name: list(BOUNDS[name]) for name in PARAMETERS},
    }
    (OUT_DIR / "run_config.json").write_text(
        json.dumps(configuration, indent=2),
        encoding="utf-8",
    )


def save_fit_plots(
    voltage: np.ndarray,
    measured_current: np.ndarray,
    result: SimulationResult,
) -> None:
    import matplotlib.pyplot as plt

    simulated_current = aligned_simulation_current(result, len(measured_current))

    plt.figure()
    plt.semilogy(
        voltage,
        np.abs(measured_current) + I_FLOOR,
        ".",
        markersize=3,
        label="measurement",
    )
    plt.semilogy(
        voltage,
        np.abs(simulated_current) + I_FLOOR,
        linewidth=1.2,
        label="simulation",
    )
    plt.grid(True, which="both", linestyle="--", alpha=0.35)
    plt.xlabel("command voltage (V)")
    plt.ylabel("|I| (A)")
    plt.title("Best fitted I-V response")
    plt.legend()
    plt.tight_layout()
    plt.savefig(OUT_DIR / "best_fit_logabs.png", dpi=180)
    plt.close()

    plt.figure()
    plt.yscale("symlog", linthresh=1e-9)
    plt.plot(voltage, measured_current, ".", markersize=3, label="measurement")
    plt.plot(voltage, simulated_current, linewidth=1.2, label="simulation")
    plt.grid(True, which="both", linestyle="--", alpha=0.35)
    plt.xlabel("command voltage (V)")
    plt.ylabel("I (A)")
    plt.title("Best fitted I-V response")
    plt.legend()
    plt.tight_layout()
    plt.savefig(OUT_DIR / "best_fit_symlog.png", dpi=180)
    plt.close()

    plt.figure()
    plt.plot(result.time, result.x, linewidth=1.1, label="x")
    plt.plot(result.time, result.xh, linewidth=1.1, label="xh")
    plt.grid(True, linestyle="--", alpha=0.35)
    plt.xlabel("time (s)")
    plt.ylabel("internal state")
    plt.title("Internal-state evolution")
    plt.legend()
    plt.tight_layout()
    plt.savefig(OUT_DIR / "best_state_vs_time.png", dpi=180)
    plt.close()


def downsample_trajectory(
    voltage: np.ndarray,
    current: np.ndarray,
    target_count: int,
) -> tuple[np.ndarray, np.ndarray]:
    if len(voltage) <= target_count:
        return voltage.copy(), current.copy()
    indices = np.linspace(0, len(voltage) - 1, target_count).astype(int)
    return voltage[indices], current[indices]


# =============================================================================
# Main workflow
# =============================================================================


def main() -> None:
    ensure_directories()

    if not NGSPICE.exists():
        raise FileNotFoundError(
            "NGSpice was not found. Install it so the 'ngspice' command is "
            "available, or place ngspice.exe in the repository root."
        )

    data_path = select_measurement_path()
    voltage_full, current_full = read_measurement(data_path)
    icomp = estimate_positive_compliance(voltage_full, current_full)
    export_run_configuration(data_path, icomp)

    voltage_coarse, current_coarse = downsample_trajectory(
        voltage_full,
        current_full,
        COARSE_POINT_TARGET,
    )

    rng = np.random.default_rng(RANDOM_SEED)

    print("\n[STAGE 1] Coarse PSO")
    coarse_objective = make_objective(
        voltage_coarse,
        current_coarse,
        icomp,
        stage="coarse",
    )
    theta_coarse, cost_coarse, history_coarse = run_pso(
        objective=coarse_objective,
        particle_count=N_PARTICLES_COARSE,
        iteration_count=N_ITERATIONS_COARSE,
        rng=rng,
    )

    print("\n[STAGE 2] Refined PSO")
    refine_objective = make_objective(
        voltage_full,
        current_full,
        icomp,
        stage="refine",
    )
    theta_best, cost_best, history_refine = run_pso(
        objective=refine_objective,
        particle_count=N_PARTICLES_REFINE,
        iteration_count=N_ITERATIONS_REFINE,
        rng=rng,
        initial_center=theta_coarse,
    )

    export_theta(theta_best)
    pd.DataFrame(history_coarse).to_csv(
        OUT_DIR / "pso_history_coarse.csv", index=False
    )
    pd.DataFrame(history_refine).to_csv(
        OUT_DIR / "pso_history_refine.csv", index=False
    )

    final_result = run_simulation(
        theta_best,
        voltage_full,
        icomp,
        tag="best",
    )
    if final_result is None:
        raise RuntimeError("The final NGSpice simulation failed.")

    final_frame = pd.DataFrame(
        {
            "time": final_result.time,
            "Vcmd": final_result.vcmd,
            "Vp": final_result.vp,
            "I": final_result.current,
            "x": final_result.x,
            "xh": final_result.xh,
        }
    )
    final_frame.to_csv(OUT_DIR / "best_simulation.csv", index=False)
    save_fit_plots(voltage_full, current_full, final_result)

    summary = pd.DataFrame(
        [
            {
                "stage": "coarse",
                "best_cost": cost_coarse,
            },
            {
                "stage": "refine",
                "best_cost": cost_best,
            },
        ]
    )
    summary.to_csv(OUT_DIR / "fit_summary.csv", index=False)

    print("\n[COMPLETE]")
    print(f"Best cost: {cost_best:.6g}")
    print(f"Output directory: {OUT_DIR}")
    print("Generated core artifacts:")
    print("  - fitdeck_embedded.cir")
    print("  - theta_best.csv")
    print("  - best_simulation.csv")
    print("  - best_fit_logabs.png")
    print("  - best_fit_symlog.png")
    print("  - best_state_vs_time.png")


if __name__ == "__main__":
    main()
